"""
Emit a C header with a TFLite model as a byte array.

microWakeWord's trainer already produces the int8 streaming .tflite we
ship to the device — this script is purely a post-processing step:

* esp-tflite-micro on ESP32-S3 loads models from a compile-time byte
  array much more easily than from SPIFFS (no FS mount, no error paths,
  no RAM copy on boot). So we wrap the .tflite bytes in a `const unsigned
  char[]` and include it from the firmware.
* We keep this as a .py file (rather than inlining into the notebook)
  so the byte-layout + alignment attribute is version-controlled.
  The firmware depends on `__attribute__((aligned(8)))` — TFLite's
  flatbuffer reader will fault without it.
"""

from __future__ import annotations

from pathlib import Path


def dump_as_c_header(tflite_path: Path, header_path: Path, var_name: str) -> None:
    """Write a C header exposing the .tflite file as a byte array.

    Args:
        tflite_path: Source .tflite file produced by microwakeword.
        header_path: Destination .h path (will overwrite).
        var_name: C symbol name for the array, e.g. `hey_beni_tflite`.
    """

    raw = Path(tflite_path).read_bytes()
    lines = [
        "// Auto-generated by ml/wake_word/scripts/dump_c_header.py.",
        "// DO NOT EDIT: regenerate by re-running the training notebook.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"extern const unsigned char {var_name}[];",
        f"extern const size_t {var_name}_len;",
        "",
        # aligned(8) is required — esp-tflite-micro reads the flatbuffer
        # directly from flash without copying, and misaligned access
        # faults on ESP32-S3.
        f"const unsigned char {var_name}[] __attribute__((aligned(8))) = {{",
    ]
    # 12 bytes per line keeps the generated header diff-friendly without
    # ballooning line count for a ~40 kB model.
    for i in range(0, len(raw), 12):
        chunk = raw[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {var_name}_len = {len(raw)};")
    lines.append("")

    Path(header_path).parent.mkdir(parents=True, exist_ok=True)
    Path(header_path).write_text("\n".join(lines))


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("tflite", type=Path)
    ap.add_argument("header", type=Path)
    ap.add_argument("--var", default="hey_beni_tflite")
    args = ap.parse_args()

    dump_as_c_header(args.tflite, args.header, args.var)
    print(f"wrote {args.header} ({args.header.stat().st_size} B)")
