"""
Export a trained microWakeWord Keras model to int8 TFLite for the
ESP32-S3 firmware, and produce a minimal metrics report.

microWakeWord ships its own export helper inside its training loop,
but we keep a thin wrapper here so the notebook has a single
well-named entry point and so post-training quantisation params
(representative dataset, input/output quantisation targets) are
version-controlled alongside the rest of the pipeline.

Int8 is non-negotiable: the firmware runs on ESP32-S3 using
esp-tflite-micro, which only gets real performance on int8 quantised
graphs — float graphs would run but at maybe 3-5x the latency,
breaking the always-on listening budget.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

import numpy as np


def representative_dataset_gen(spectrograms: Iterable[np.ndarray]):
    """Yield calibration tensors for TFLite post-training quantisation.

    The converter needs a representative distribution of activation
    ranges to pick int8 scales/zero-points. We feed a few hundred
    real training spectrograms — using test-set spectrograms would
    leak that set into quantisation, so the caller should pass
    training-set samples only.
    """

    for spec in spectrograms:
        # Input rank must match the model's: (1, T, F, 1) for most
        # microWakeWord configs. If the array is already 2D (T, F)
        # we add the batch + channel dims on the fly.
        arr = np.asarray(spec, dtype=np.float32)
        if arr.ndim == 2:
            arr = arr[np.newaxis, :, :, np.newaxis]
        elif arr.ndim == 3:
            arr = arr[np.newaxis, ...]
        yield [arr]


def export_to_tflite(
    keras_model,
    representative_spectrograms: list[np.ndarray],
    out_tflite: Path,
) -> int:
    """Convert a Keras wake-word model to int8 TFLite on disk.

    Returns the size of the written file in bytes, which we log so
    we can catch accidental bloat (e.g. a dense layer leaking into
    the graph) without having to re-open the model.
    """

    import tensorflow as tf

    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_dataset_gen(
        representative_spectrograms
    )
    # Full int8 — inputs, outputs, and activations all quantised.
    # esp-tflite-micro is happiest with a fully-int8 graph; any
    # float IO forces the interpreter to add dequant ops that cost
    # kB of flash and ms of latency.
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS_INT8
    ]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_bytes = converter.convert()
    out_tflite.parent.mkdir(parents=True, exist_ok=True)
    out_tflite.write_bytes(tflite_bytes)
    return len(tflite_bytes)


def write_metrics_report(
    metrics: dict,
    out_path: Path,
) -> None:
    """Dump a human-readable metrics.json next to the .tflite.

    Minimal on purpose — FRR at a few fixed FAR operating points is
    what we actually care about. TensorBoard has the fine-grained
    curves if we need to dig in.
    """

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(metrics, indent=2))


def dump_as_c_header(tflite_path: Path, header_path: Path, var_name: str) -> None:
    """Emit a C header with the model as a byte array.

    The firmware include path wants a compile-time-constant byte
    array (esp-tflite-micro can't mmap from SPIFFS without extra
    plumbing we'd rather avoid). We keep both the raw .tflite (for
    re-use) and this header (for compile) in artifacts/.
    """

    raw = tflite_path.read_bytes()
    lines = [
        "// Auto-generated by ml/wake_word/scripts/export_model.py.",
        "// DO NOT EDIT: regenerate by re-running the training notebook.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"extern const unsigned char {var_name}[];",
        f"extern const size_t {var_name}_len;",
        "",
        f"const unsigned char {var_name}[] __attribute__((aligned(8))) = {{",
    ]
    # 12 bytes per line keeps the generated header readable without
    # making it gigantic.
    for i in range(0, len(raw), 12):
        chunk = raw[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {var_name}_len = {len(raw)};")
    lines.append("")

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(lines))
